export const FOURWORDS = [
    'ABBA', 'ABBE', 'ABLE', 'ABLY', 'ACES', 'ACHE', 'ACID', 'ACME', 'ACNE', 'ACRE',
    'ACTA', 'ACTS', 'ACYL', 'ADDS', 'AERO', 'AFAR', 'AFRO', 'AGAR', 'AGED', 'AGER',
    'AGES', 'AIDA', 'AIDE', 'AIDS', 'AIMS', 'AIRS', 'AIRY', 'AJAR', 'AKIN', 'ALAN',
    'ALAS', 'ALBA', 'ALEC', 'ALFA', 'ALGA', 'ALLY', 'ALMA', 'ALMS', 'ALOE', 'ALPS',
    'ALSO', 'ALTO', 'ALUM', 'AMEN', 'AMES', 'AMID', 'AMIN', 'AMIR', 'AMIS', 'AMMO',
    'AMPS', 'ANAL', 'ANCE', 'ANEW', 'ANNA', 'ANNO', 'ANON', 'ANTE', 'ANTI', 'ANTS',
    'ANUS', 'APES', 'APEX', 'APSE', 'AQUA', 'ARCH', 'ARCO', 'ARCS', 'ARDS', 'AREA',
    'ARES', 'ARIA', 'ARID', 'ARMS', 'ARMY', 'ARSE', 'ARTS', 'ASKS', 'ATOM', 'ATOP',
    'AULD', 'AUNT', 'AURA', 'AUTO', 'AVER', 'AVID', 'AWAY', 'AWED', 'AWRY', 'AXEL',
    'AXES', 'AXIS', 'AXLE', 'AXON', 'BAAL', 'BABA', 'BABE', 'BABU', 'BABY', 'BACH',
    'BACK', 'BADE', 'BAGS', 'BAHT', 'BAIL', 'BAIT', 'BAKE', 'BALD', 'BALE', 'BALK',
    'BALL', 'BALM', 'BAND', 'BANE', 'BANG', 'BANK', 'BANS', 'BAPU', 'BARB', 'BARD',
    'BARE', 'BARK', 'BARN', 'BARS', 'BASE', 'BASH', 'BASK', 'BASS', 'BAST', 'BATE',
    'BATH', 'BATS', 'BAUD', 'BAYS', 'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT',
    'BEAU', 'BECK', 'BEDE', 'BEDS', 'BEEF', 'BEEN', 'BEEP', 'BEER', 'BEES', 'BEET',
    'BEGS', 'BEIN', 'BELL', 'BELT', 'BEND', 'BENE', 'BENI', 'BENT', 'BERG', 'BEST',
    'BETA', 'BETH', 'BETS', 'BHAI', 'BIAS', 'BIDE', 'BIDS', 'BIEN', 'BIER', 'BIKE',
    'BILE', 'BILL', 'BIND', 'BING', 'BINS', 'BIOS', 'BIRD', 'BITE', 'BITS', 'BLAH',
    'BLED', 'BLEW', 'BLOB', 'BLOC', 'BLOG', 'BLOT', 'BLOW', 'BLUE', 'BLUR', 'BOAR',
    'BOAS', 'BOAT', 'BOCK', 'BODE', 'BODY', 'BOGS', 'BOIL', 'BOIS', 'BOLD', 'BOLL',
    'BOLT', 'BOMB', 'BONA', 'BOND', 'BONE', 'BONY', 'BOOK', 'BOOL', 'BOOM', 'BOON',
    'BOOT', 'BORA', 'BORE', 'BORN', 'BOSS', 'BOTH', 'BOUT', 'BOWL', 'BOWS', 'BOYS',
    'BRAD', 'BRAG', 'BRAN', 'BRAS', 'BRAT', 'BRAY', 'BRED', 'BREW', 'BRIG', 'BRIM',
    'BRIT', 'BROS', 'BROW', 'BUCK', 'BUDS', 'BUFF', 'BUGS', 'BULB', 'BULK', 'BULL',
    'BUMP', 'BUMS', 'BUND', 'BUNK', 'BUNS', 'BUOY', 'BURG', 'BURN', 'BURR', 'BURY',
    'BUSH', 'BUSS', 'BUST', 'BUSY', 'BUTE', 'BUTT', 'BUYS', 'BUZZ', 'BYTE', 'CABS',
    'CADE', 'CAFE', 'CAGE', 'CAIN', 'CAKE', 'CALF', 'CALL', 'CALM', 'CAME', 'CAMP',
    'CANE', 'CANS', 'CAPE', 'CAPS', 'CARA', 'CARD', 'CARE', 'CARP', 'CARS', 'CART',
    'CASE', 'CASH', 'CASK', 'CAST', 'CATS', 'CAVE', 'CEDE', 'CELL', 'CENT', 'CERN',
    'CHAD', 'CHAR', 'CHAT', 'CHAW', 'CHEF', 'CHIC', 'CHIN', 'CHIP', 'CHIT', 'CHOP',
    'CHOW', 'CHUG', 'CHUM', 'CINE', 'CITY', 'CLAD', 'CLAM', 'CLAN', 'CLAP', 'CLAW',
    'CLAY', 'CLEF', 'CLEW', 'CLIP', 'CLOD', 'CLOG', 'CLOP', 'CLOT', 'CLUB', 'CLUE',
    'COAL', 'COAT', 'COAX', 'COBS', 'COCK', 'COCO', 'CODA', 'CODE', 'CODS', 'COED',
    'COIL', 'COIN', 'COKE', 'COLA', 'COLD', 'COLS', 'COLT', 'COMA', 'COMB', 'COME',
    'COOK', 'COOL', 'COON', 'COOP', 'COOS', 'COOT', 'COPE', 'COPS', 'COPY', 'CORD',
    'CORE', 'CORK', 'CORN', 'COST', 'COTS', 'COUP', 'COVE', 'COWL', 'COWS', 'COZY',
    'CRAB', 'CRAG', 'CRAM', 'CRAP', 'CRAW', 'CREW', 'CRIB', 'CRIS', 'CROP', 'CROW',
    'CRUD', 'CRUX', 'CUBE', 'CUBS', 'CUDS', 'CUES', 'CUFF', 'CULL', 'CULT', 'CUMS',
    'CURE', 'CURL', 'CURT', 'CUTS', 'CYAN', 'CYST', 'CZAR', 'DABS', 'DACE', 'DAFT',
    'DAIS', 'DALE', 'DAME', 'DAMP', 'DAMS', 'DANE', 'DANK', 'DARE', 'DARK', 'DARN',
    'DART', 'DASH', 'DATA', 'DATE', 'DAUB', 'DAWN', 'DAZE', 'DEAD', 'DEAF', 'DEAL',
    'DEAN', 'DEAR', 'DECK', 'DEED', 'DEEM', 'DEEP', 'DEER', 'DEFT', 'DEFY', 'DELI',
    'DELL', 'DENT', 'DENY', 'DESK', 'DEWS', 'DEWY', 'DIAL', 'DICE', 'DICK', 'DIED',
    'DIES', 'DIET', 'DIME', 'DIMS', 'DINE', 'DING', 'DINS', 'DINT', 'DIPS', 'DIPT',
    'DIRE', 'DIRT', 'DISC', 'DISH', 'DISK', 'DIVE', 'DOCK', 'DOES', 'DOFF', 'DOGS',
    'DOLE', 'DOLL', 'DOLT', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DORA', 'DOSE', 'DOTE',
    'DOUR', 'DOVE', 'DOWN', 'DOZE', 'DRAB', 'DRAG', 'DRAM', 'DRAW', 'DRAY', 'DREW',
    'DRIP', 'DROP', 'DRUB', 'DRUG', 'DRUM', 'DUAL', 'DUBS', 'DUCK', 'DUCT', 'DUES',
    'DUFF', 'DUKE', 'DULL', 'DUMB', 'DUMP', 'DUNE', 'DUNG', 'DUNK', 'DUNS', 'DUNT',
    'DUPE', 'DUSK', 'DUST', 'DUTY', 'DYAD', 'DYED', 'DYER', 'DYES', 'DYKE', 'EACH',
    'EARL', 'EARN', 'EARS', 'EASE', 'EAST', 'EASY', 'EATS', 'EAVE', 'EBBS', 'EBON',
    'ECHO', 'EDDY', 'EDEN', 'EDGE', 'EDGY', 'EDIT', 'EGAL', 'EGGS', 'EGGY', 'EGOS',
    'EIRE', 'EKES', 'ELAN', 'ELDS', 'ELFS', 'ELIA', 'ELKS', 'ELLA', 'ELLS', 'ELSE',
    'EMIT', 'EMMA', 'EMUS', 'ENDS', 'ENVY', 'EONS', 'EPEE', 'EPOS', 'ERAS', 'ERGO',
    'ERIC', 'ERIN', 'ERST', 'EVES', 'EYED', 'EYER', 'EYES', 'EYRY', 'FACE', 'FACT',
    'FADE', 'FAIL', 'FAIN', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FANG', 'FANS', 'FARM',
    'FAST', 'FATE', 'FAWN', 'FEAR', 'FEAT', 'FEED', 'FEEL', 'FEES', 'FEET', 'FELL',
    'FELT', 'FEND', 'FERN', 'FEST', 'FEUD', 'FIEF', 'FIFE', 'FIGS', 'FILE', 'FILL',
    'FILM', 'FIND', 'FINE', 'FINK', 'FIRE', 'FIRM', 'FISH', 'FIST', 'FITS', 'FIVE',
    'FIZZ', 'FLAB', 'FLAG', 'FLAK', 'FLAM', 'FLAP', 'FLAT', 'FLAW', 'FLAX', 'FLAY',
    'FLEA', 'FLED', 'FLEE', 'FLEW', 'FLIP', 'FLOE', 'FLOG', 'FLOP', 'FLOW', 'FLUB',
    'FLUE', 'FOAL', 'FOAM', 'FOBS', 'FOCI', 'FOES', 'FOGS', 'FOGY', 'FOIL', 'FOLD',
    'FOLK', 'FOND', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD', 'FORE', 'FORK', 'FORM',
    'FORT', 'FOUL', 'FOUR', 'FOWL', 'FRET', 'FREY', 'FRIZ', 'FROG', 'FROM', 'FROW',
    'FUEL', 'FULL', 'FUME', 'FUND', 'FUNK', 'FURL', 'FURS', 'FURY', 'FUSE', 'FUSS',
    'FUTZ', 'FUZE', 'FUZZ', 'GABS', 'GADS', 'GAGE', 'GAIN', 'GAIT', 'GALE', 'GALL',
    'GALS', 'GAMA', 'GAME', 'GANG', 'GAPS', 'GARB', 'GARS', 'GASH', 'GASP', 'GATE',
    'GATS', 'GAUD', 'GAUM', 'GAUN', 'GAUR', 'GAVE', 'GAWK', 'GAWS', 'GAYS', 'GAZE',
    'GEAR', 'GEEK', 'GELD', 'GELS', 'GELT', 'GEMS', 'GENE', 'GENS', 'GENT', 'GENU',
    'GERM', 'GEST', 'GETS', 'GEUM', 'GHAT', 'GIBE', 'GIFT', 'GILD', 'GILL', 'GILT',
    'GIMP', 'GINS', 'GIRD', 'GIRL', 'GIRT', 'GIST', 'GIVE', 'GLAD', 'GLEE', 'GLEN',
    'GLIB', 'GLOB', 'GLOM', 'GLOW', 'GLUE', 'GLUM', 'GLUT', 'GOAD', 'GOAL', 'GOAT',
    'GOER', 'GOES', 'GOLD', 'GOLF', 'GONE', 'GONG', 'GOOD', 'GOOF', 'GOON', 'GORE',
    'GORY', 'GOSH', 'GOUT', 'GOWN', 'GRAB', 'GRAD', 'GRAY', 'GREE', 'GREW', 'GREY',
    'GRID', 'GRIM', 'GRIN', 'GRIP', 'GRIT', 'GROG', 'GROW', 'GRUB', 'GUCK', 'GUYS',
    'GYMS', 'GYPS', 'GYRO', 'HACK', 'HAFT', 'HAGS', 'HAIL', 'HAIR', 'HALE', 'HALF',
    'HALL', 'HALO', 'HALT', 'HAND', 'HANG', 'HANK', 'HAPS', 'HARD', 'HARE', 'HARK',
    'HARM', 'HART', 'HASH', 'HASP', 'HATE', 'HATH', 'HATS', 'HAUL', 'HAVE', 'HAWK',
    'HAWS', 'HAYS', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT', 'HEBE', 'HECK', 'HEED',
    'HEEL', 'HEFT', 'HELD', 'HELL', 'HELM', 'HELO', 'HELP', 'HEME', 'HEMP', 'HERB',
    'HERD', 'HERE', 'HERO', 'HERS', 'HEWN', 'HEWS', 'HICK', 'HIDE', 'HIGH', 'HIKE',
    'HILL', 'HILT', 'HIND', 'HINT', 'HIPS', 'HIRE', 'HITS', 'HIVE', 'HOAX', 'HOCK',
    'HOED', 'HOER', 'HOES', 'HOGS', 'HOKE', 'HOLD', 'HOLE', 'HOLM', 'HOLY', 'HOME',
    'HONE', 'HONG', 'HONK', 'HOOD', 'HOOF', 'HOOK', 'HOOP', 'HOOT', 'HOPS', 'HORN',
    'HOSE', 'HOST', 'HOUR', 'HOWL', 'HOYA', 'HUBS', 'HUED', 'HUES', 'HUFF', 'HUGE',
    'HUGS', 'HULA', 'HULK', 'HULL', 'HUMP', 'HUMS', 'HUNG', 'HUNK', 'HUNS', 'HUNT',
    'HURL', 'HURT', 'HUSH', 'HUSK', 'HUSS', 'HUTS', 'HYMN', 'HYPO', 'IBEX', 'IBIS',
    'ICED', 'ICES', 'ICON', 'IDEA', 'IDES', 'IDLE', 'IDOL', 'IFFY', 'IKON', 'ILLS',
    'IMPS', 'INCA', 'INCH', 'INKS', 'INKY', 'INLY', 'INRO', 'INTO', 'IONS', 'IOTA',
    'IOWA', 'IRED', 'IRIS', 'IRKS', 'IRON', 'ISLE', 'ISMS', 'ITCH', 'ITEM', 'IWIS',
    'JABS', 'JADE', 'JAGS', 'JAIL', 'JAMB', 'JAMS', 'JANE', 'JARS', 'JATO', 'JAUN',
    'JAWS', 'JAYS', 'JAZZ', 'JEAN', 'JEER', 'JEFF', 'JELL', 'JERK', 'JESS', 'JEST',
    'JETS', 'JIBE', 'JIGS', 'JILT', 'JIVE', 'JOBS', 'JOCK', 'JOES', 'JOEY', 'JOGS',
    'JOHN', 'JOIN', 'JOKE', 'JOLT', 'JOWL', 'JOYS', 'JUDE', 'JUDO', 'JUDY', 'JUKE',
    'JUMP', 'JUNE', 'JUNK', 'JURY', 'JUST', 'JUTE', 'KAIL', 'KALE', 'KANE', 'KATA',
    'KAVA', 'KAYS', 'KEEL', 'KEEN', 'KEEP', 'KEGS', 'KELL', 'KENO', 'KENS', 'KEPI',
    'KEPT', 'KERB', 'KERN', 'KEYS', 'KHAN', 'KHAT', 'KICK', 'KIDS', 'KILL', 'KILN',
    'KILO', 'KILT', 'KIND', 'KING', 'KINK', 'KIPS', 'KIRK', 'KISS', 'KITE', 'KITH',
    'KITS', 'KIWI', 'KNEE', 'KNEW', 'KNIT', 'KNOB', 'KNOT', 'KNOW', 'KOCH', 'KONG',
    'KUDO', 'KUDO', 'KULA', 'KUNE', 'KURI', 'KURU', 'KUTA', 'LACE', 'LACK', 'LACS',
    'LACY', 'LADS', 'LADY', 'LAGS', 'LAID', 'LAIN', 'LAIR', 'LAKE', 'LAMB', 'LAME',
    'LAMP', 'LAND', 'LANE', 'LANG', 'LANK', 'LAPS', 'LARD', 'LARK', 'LASH', 'LASS',
    'LAST', 'LATE', 'LATH', 'LATI', 'LATS', 'LAUD', 'LAVA', 'LAWN', 'LAWS', 'LAYS',
    'LEAD', 'LEAF', 'LEAK', 'LEAN', 'LEAP', 'LEAR', 'LEAS', 'LEEK', 'LEER', 'LEES',
    'LEFT', 'LEGS', 'LEIS', 'LENS', 'LENT', 'LEOS', 'LESS', 'LEST', 'LETS', 'LEWD',
    'LIAR', 'LICE', 'LICK', 'LIDO', 'LIDS', 'LIED', 'LIEU', 'LIFE', 'LIFT', 'LIKE',
    'LILT', 'LILY', 'LIMA', 'LIMB', 'LIME', 'LIMP', 'LIMY', 'LINE', 'LING', 'LINK',
    'LINT', 'LION', 'LIRA', 'LIRE', 'LISP', 'LIST', 'LITE', 'LITS', 'LIVE', 'LOAD',
    'LOAF', 'LOAM', 'LOAN', 'LOCK', 'LOCO', 'LODE', 'LOFT', 'LOGO', 'LOGS', 'LOGY',
    'LOIN', 'LOLL', 'LONE', 'LONG', 'LOOK', 'LOOM', 'LOON', 'LOOP', 'LOOT', 'LOPE',
    'LOPS', 'LORD', 'LORE', 'LOSE', 'LOSS', 'LOST', 'LOTA', 'LOTS', 'LOUD', 'LOVE',
    'LOWE', 'LOWS', 'LUCK', 'LUCY', 'LUGE', 'LULL', 'LUMP', 'LUNE', 'LUNG', 'LUNK',
    'LURE', 'LURK', 'LUSH', 'LUST', 'LUTE', 'LUXE', 'LYNX', 'LYRA', 'LYRE', 'MACE',
    'MACH', 'MACK', 'MADE', 'MADS', 'MAFF', 'MAGE', 'MAGI', 'MAID', 'MAIL', 'MAIM',
    'MAIN', 'MAJO', 'MAKE', 'MALE', 'MALL', 'MALT', 'MAMA', 'MANE', 'MANG', 'MANO',
    'MAPS', 'MARA', 'MARE', 'MARK', 'MARL', 'MARS', 'MART', 'MARY', 'MASK', 'MASS',
    'MAST', 'MATE', 'MATS', 'MAUL', 'MAWK', 'MAWR', 'MAYA', 'MAYS', 'MEAD', 'MEAL',
    'MEAN', 'MEAT', 'MEET', 'MEEK','MELD', 'MELL', 'MELT', 'MEME', 'MEMO', 'MEND', 'MENU', 'MEOU', 'MERE',
    'MESH', 'MESS', 'META', 'METH', 'MEWS', 'MICA', 'MICE', 'MICK', 'MIDI', 'MIDS',
    'MIEN', 'MILD', 'MILE', 'MILK', 'MILL', 'MILT', 'MIME', 'MIND', 'MINE', 'MING',
    'MINI', 'MINK', 'MINT', 'MINX', 'MIRE', 'MIRK', 'MIRY', 'MISE', 'MISO', 'MISS',
    'MIST', 'MITE', 'MITT', 'MITY', 'MIXT', 'MOAN', 'MOAS', 'MOAT', 'MOBS', 'MOCK',
    'MODE', 'MODS', 'MOIL', 'MOJO', 'MOJO', 'MOKA', 'MOLA', 'MOLD', 'MOLE', 'MOLL',
    'MOLS', 'MOLT', 'MOLY', 'MOME', 'MOMI', 'MOMS', 'MONK', 'MONO', 'MONS', 'MONY',
    'MOOD', 'MOOL', 'MOON', 'MOOR', 'MOOS', 'MOOT', 'MOPE', 'MOPS', 'MOPY', 'MORA',
    'MORE', 'MORN', 'MORS', 'MORT', 'MOSH', 'MOSK', 'MOSS', 'MOST', 'MOTE', 'MOTH',
    'MOTS', 'MOTT', 'MOUE', 'MOVE', 'MOWN', 'MOWS', 'MOXA', 'MUCH', 'MUCK', 'MUDS',
    'MUFF', 'MUGS', 'MULE', 'MULL', 'MULT', 'MUMM', 'MUMP', 'MUMS', 'MUNI', 'MUNS',
    'MUON', 'MURA', 'MURE', 'MURK', 'MURR', 'MUSE', 'MUSH', 'MUSK', 'MUSS', 'MUST',
    'MUTE', 'MUTS', 'MUTT', 'MYNA', 'MYTH', 'NABS', 'NADA', 'NAFF', 'NAGS', 'NAIF',
    'NAIL', 'NAME', 'NANA', 'NANS', 'NAOI', 'NAOS', 'NAPA', 'NAPE', 'NAPS', 'NARC',
    'NARD', 'NARK', 'NARY', 'NAYS', 'NAZE', 'NEAP', 'NEAR', 'NEAT', 'NEBS', 'NECK',
    'NEED', 'NEEM', 'NEEP', 'NEFS', 'NEGS', 'NEIF', 'NEST', 'NETS', 'NETT', 'NEUK',
    'NEUM', 'NEVE', 'NEVI', 'NEWS', 'NEWT', 'NEXT', 'NIBS', 'NICE', 'NICK', 'NIDE',
    'NIDI', 'NIGH', 'NILL', 'NILS', 'NIMS', 'NINE', 'NIPA', 'NIPS', 'NISI', 'NITE',
    'NITS', 'NIXE', 'NIXY', 'NOBS', 'NOCK', 'NODE', 'NODI', 'NODS', 'NOEL', 'NOES',
    'NOGG', 'NOGS', 'NOIL', 'NOIR', 'NOLO', 'NOMA', 'NOME', 'NOMS', 'NONA', 'NONE',
    'NOOK', 'NOON', 'NOPE', 'NORI', 'NORM', 'NOSE', 'NOSH', 'NOSY', 'NOTA', 'NOTE',
    'NOTS', 'NOUS', 'NOVA', 'NOWS', 'NOWT', 'NUBS', 'NUDE', 'NUKE', 'NULL', 'NUMB',
    'NUNS', 'NURD', 'NURL', 'NUTS', 'OAKS', 'OARS', 'OAST', 'OATH', 'OATS', 'OBEY',
    'OBIA', 'OBIS', 'OBIT', 'OBOE', 'OBOL', 'OCAS', 'OCCY', 'OCHS', 'ODDS', 'ODEA',
    'ODES', 'ODIC', 'OHED', 'OHIA', 'OHMS', 'OILS', 'OILY', 'OINK', 'OKAS', 'OKAY',
    'OKRA', 'OLDS', 'OLDY', 'OLEA', 'OLEO', 'OLES', 'OLIO', 'OLLA', 'OMEN', 'OMER',
    'OMIT', 'ONCE', 'ONES', 'ONLY', 'ONOS', 'ONTO', 'ONUS', 'ONYX', 'OOHS', 'OOPS',
    'OOSE', 'OOTS', 'OOZE', 'OOZY', 'OPAH', 'OPAL', 'OPED', 'OPEN', 'OPES', 'OPTS',
    'ORAD', 'ORAL', 'ORBS', 'ORCA', 'ORCS', 'ORDO', 'ORDS', 'ORES', 'ORGY', 'ORLE',
    'ORRA', 'ORTS', 'ORYX', 'OSES', 'OTIC', 'OUCH', 'OUDS', 'OULK', 'OURS', 'OUST',
    'OUTS', 'OUZO', 'OVAL', 'OVEN', 'OVER', 'OVUM', 'OWED', 'OWES', 'OWLS', 'OWNS',
    'OYER', 'OYES', 'OYEZ', 'PACA', 'PACE', 'PACK', 'PACO', 'PACS', 'PACT', 'PADI',
    'PADS', 'PAGE', 'PAID', 'PAIK', 'PAIL', 'PAIN', 'PAIR', 'PALE', 'PALL', 'PALM',
    'PALP', 'PALS', 'PALY', 'PAMS', 'PAND', 'PANE', 'PANG', 'PANS', 'PANT', 'PAPA',
    'PAPS', 'PARA', 'PARD', 'PARE', 'PARK', 'PARS', 'PART', 'PASE', 'PASH', 'PASS',
    'PAST', 'PATE', 'PATH', 'PATS', 'PATY', 'PAVE', 'PAWS', 'PAYS', 'PEAG', 'PEAK',
    'PEAL', 'PEAN', 'PEAR', 'PEAS', 'PEAT', 'PECH', 'PECK', 'PECS', 'PEDS', 'PEED',
    'PEEK', 'PEEL', 'PEEN', 'PEEP', 'PEER', 'PEES', 'PEGS', 'PEHS', 'PEIN', 'PEKE',
    'PELE', 'PELL', 'PELT', 'PEND', 'PENS', 'PENT', 'PEON', 'PEPO', 'PEPS', 'PERI',
    'PERK', 'PERM', 'PERP', 'PERT', 'PESO', 'PEST', 'PETS', 'PEWS', 'PFFT', 'PFUI',
    'PHAT', 'PHEW', 'PHIS', 'PHIZ', 'PHOH', 'PHON', 'PHOT', 'PHPH', 'PHUT', 'PIAL',
    'PIAN', 'PIAS', 'PICA', 'PICE', 'PICK', 'PICS', 'PIED', 'PIER', 'PIES', 'PIGS',
    'PIKA', 'PIKE', 'PIKI', 'PILE', 'PILI', 'PILL', 'PILY', 'PIMA', 'PIMP', 'PINA',
    'PINE', 'PING', 'PINK', 'PINS', 'PINT', 'PINY', 'PION', 'PIOY', 'PIPE', 'PIPS',
    'PIPY', 'PIRN', 'PIRS', 'PISH', 'PISO', 'PISS', 'PITA', 'PITH', 'PITS', 'PITY',
    'PIXY', 'PIZE', 'PLAN', 'PLAT', 'PLAY', 'PLEA', 'PLEB', 'PLED', 'PLEW', 'PLEX',
    'PLIE', 'PLOD', 'PLOP', 'PLOT', 'PLOW', 'PLOY', 'PLUG', 'PLUM', 'PLUS', 'POCK',
    'POCO', 'PODS', 'POEM', 'POET', 'POIS', 'POKE', 'POKY', 'POLE', 'POLL', 'POLS',
    'POLY', 'POME', 'POMO', 'POMP', 'POND', 'PONE', 'PONG', 'PONS', 'PONY', 'POOD',
    'POOF', 'POOH', 'POOK', 'POOL', 'POON', 'POOP', 'POOR', 'POOS', 'POOT', 'POPE',
    'POPS', 'PORE', 'PORK', 'PORN', 'PORT', 'POSE', 'POSH', 'POST', 'POSY', 'POTS',
    'POUF', 'POUR', 'POUT', 'POWS', 'PRAM', 'PRAT', 'PRAU', 'PRAY', 'PREP', 'PREX',
    'PREY', 'PREZ', 'PRIG', 'PRIM', 'PROA', 'PROD', 'PROF', 'PROG', 'PROS', 'PROW',
    'PTUI', 'PUCE', 'PUCK', 'PUFF', 'PUGH', 'PUKE', 'PULA', 'PULE', 'PULI', 'PULK',
    'PULL', 'PULP', 'PULS', 'PUMA', 'PUMP', 'PUNA', 'PUNG', 'PUNK', 'PUNS', 'PUNT',
    'PUNY', 'PUPA', 'PUPS', 'PUPU', 'PURE', 'PURI', 'PURL', 'PURR', 'PURS', 'PUSH',
    'PUSS', 'PUTS', 'PUTT', 'PYAS', 'PYES', 'PYIC', 'PYIN', 'PYRE', 'PYRO', 'QADI',
    'QATS', 'QOPH', 'QUAD', 'QUAG', 'QUAI', 'QUAY', 'QUEY', 'QUID', 'QUIN', 'QUIP',
    'QUIT', 'QUOD', 'RACE', 'RACK', 'RACY', 'RAFF', 'RAFT', 'RAGA', 'RAGE', 'RAGG',
    'RAGI', 'RAGS', 'RAIA', 'RAID', 'RAIL', 'RAIN', 'RAJA', 'RAKE', 'RAKI', 'RALE',
    'RAMP', 'RAMS', 'RAND', 'RANG', 'RANI', 'RANK', 'RANT', 'RAPE', 'RAPS', 'RAPT',
    'RARE', 'RASE', 'RASH', 'RASP', 'RATE', 'RATH', 'RATO', 'RATS', 'RAVE', 'RAVS',
    'RAWM', 'RAWS', 'RAYA', 'RAYS', 'RAZE', 'RAZZ', 'READ', 'REAL', 'REAM', 'REAP',
    'REAR', 'REBS', 'RECK', 'RECS', 'REDD', 'REDE', 'REDO', 'REDS', 'REED', 'REEF',
    'REEK', 'REEL', 'REES','REFS',
    'REIN',
    'REIS',
    'RELY',
    'REND',
    'RENT',
    'REPS',
    'REST',
    'RETA',
    'REVS',
    'RIAL',
    'RIAS',
    'RICE',
    'RICH',
    'RICK',
    'RIDE',
    'RIFE',
    'RIFT',
    'RIGS',
    'RIME',
    'RIMS',
    'RIND',
    'RING',
    'RINK',
    'RIOT',
    'RIPE',
    'RISE',
    'RISK',
    'RITE',
    'RITZ',
    'ROAD',
    'ROAM',
    'ROAN',
    'ROAR',
    'ROBE',
    'ROBS',
    'ROCK',
    'RODE',
    'RODS',
    'ROLE',
    'ROLF',
    'ROLL',
    'ROMA',
    'ROMS',
    'ROOD',
    'ROOF',
    'ROOK',
    'ROOM',
    'ROOS',
    'ROOT',
    'ROPE',
    'RORY',
    'ROSE',
    'ROSY',
    'ROTE',
    'ROUT',
    'ROUX',
    'ROWS',
    'RUBS',
    'RUBY',
    'RUDD',
    'RUDE',
    'RUFF',
    'RUGS',
    'RUIN',
    'RULE',
    'RUMP',
    'RUNG',
    'RUNS',
    'RUSE',
    'RUSH',
    'RUSK',
    'RUST',
    'RUTH',
    'RUTS',
    'SACK',
'SADE',
'SAFE',
'SAGA',
'SAGE',
'SAGO',
'SAID',
'SAIL',
'SAKE',
'SALE',
'SALT',
'SAMA',
'SAME',
'SAMS',
'SAND',
'SANE',
'SANG',
'SANK',
'SANS',
'SANT',
'SARI',
'SARS',
'SASH',
'SATI',
'SAUL',
'SAVE',
'SAWN',
'SAWS',
'SAYS',
'SCAB',
'SCAM',
'SCAN',
'SCAR',
'SCOT',
'SCUM',
'SEAL',
'SEAM',
'SEAN',
'SEAS',
'SEAT',
'SECT',
'SEED',
'SEEK',
'SEEM',
'SEEN',
'SEEP',
'SEER',
'SEES',
'SELF',
'SELL',
'SEMI',
'SENA',
'SEND',
'SENS',
'SENT',
'SEPT',
'SERA',
'SERF',
'SESS',
'SETS',
'SEWN',
'SEXY',
'SHAD',
'SHAH',
'SHAM',
'SHAN',
'SHAW',
'SHAY',
'SHEA',
'SHED',
'SHEW',
'SHIN',
'SHIP',
'SHIT',
'SHOD',
'SHOE',
'SHOP',
'SHOT',
'SHOW',
'SHRI',
'SHUN',
'SHUT',
'SICH',
'SICK',
'SIDE',
'SIFT',
'SIGH',
'SIGN',
'SILK',
'SILL',
'SILO',
'SILT',
'SIMS',
'SIND',
'SINE',
'SING',
'SINK',
'SINS',
'SIPS',
'SIRE',
'SIRS',
'SITE',
'SITS',
'SIZE',
'SKEW',
'SKID',
'SKIM',
'SKIN',
'SKIP',
'SKIS',
'SLAB',
'SLAG',
'SLAM',
'SLAP',
'SLAY',
'SLED',
'SLEW',
'SLID',
'SLIM',
'SLIP',
'SLIT',
'SLOP',
'SLOT',
'SLOW',
'SLUG',
'SLUM',
'SLUR',
'SLUT',
'SMOG',
'SMUG',
'SNAG',
'SNAP',
'SNOB',
'SNOW',
'SNUB',
'SNUG',
'SOAK',
'SOAP',
'SOAR',
'SOBS',
'SOCK',
'SODA',
'SOFA',
'SOFT',
'SOHO',
'SOIL',
'SOLA',
'SOLD',
'SOLE',
'SOLO',
'SOMA',
'SOME',
'SONG',
'SONS',
'SOON',
'SOOT',
'SORE',
'SORT',
'SOUL',
'SOUP',
'SOUR',
'SOUS',
'SOWN',
'SOWS',
'SOYA',
'SPAM',
'SPAN',
'SPAR',
'SPAT',
'SPEC',
'SPED',
'SPIE',
'SPIN',
'SPIT',
'SPOT',
'SPUN',
'SPUR',
'STAB',
'STAG',
'STAR',
'STAT',
'STAY',
'STEM',
'STEP',
'STEW',
'STIR',
'STOP',
'STOW',
'STUB',
'STUD',
'SUBS',
'SUCH',
'SUCK',
'SUED',
'SUIT',
'SULU',
'SUMP',
'SUMS',
'SUNG',
'SUNK',
'SUNS',
'SURA',
'SURE',
'SURF',
'SWAB',
'SWAM',
'SWAN',
'SWAP',
'SWAT',
'SWAY',
'SWIM',
'SYED',
'SYNC',
'TABS',
'TABU',
'TACK',
'TACT',
'TAGS',
'TAIL',
'TAIN',
'TAIT',
'TAKE',
'TALC',
'TALE',
'TALK',
'TALL',
'TAME',
'TANA',
'TANG',
'TANK',
'TAOS',
'TAPE',
'TAPS',
'TARA',
'TARN',
'TARO',
'TART',
'TASK',
'TATE',
'TAUT',
'TAXA',
'TAXI',
'TEAK',
'TEAL',
'TEAM',
'TEAR',
'TEAS',
'TECH',
'TEEN',
'TEIL',
'TELE',
'TELL',
'TEMP',
'TEND',
'TENS',
'TENT',
'TERM',
'TERN',
'TEST',
'TETE',
'TEXT',
'THAN',
'THAR',
'THAT',
'THAW',
'THEE',
'THEM',
'THEN',
'THEY',
'THIN',
'THIS',
'THOU',
'THRO',
'THRU',
'THUD',
'THUS',
'TIAN',
'TICK',
'TICS',
'TIDE',
'TIDY',
'TIER',
'TIES',
'TILE',
'TILL',
'TILT',
'TIME',
'TINA',
'TINE',
'TING',
'TINS',
'TINT',
'TINY',
'TIPS',
'TIRE',
'TITS',
'TOAD',
'TOBY',
'TOED',
'TOES',
'TOFU',
'TOGA',
'TOIL',
'TOLD',
'TOLL',
'TOMB',
'TOME',
'TOMS',
'TONE',
'TONG',
'TONS',
'TONY',
'TOOK',
'TOOL',
'TOPS',
'TORE',
'TORI',
'TORN',
'TORO',
'TORS',
'TORT',
'TORY',
'TOSH',
'TOSS',
'TOST',
'TOTE',
'TOTS',
'TOUR',
'TOUT',
'TOWN',
'TOWS',
'TOYS',
'TRAD',
'TRAM',
'TRAP',
'TRAY',
'TREE',
'TREF',
'TREK',
'TRET',
'TREW',
'TREY',
'TRIG',
'TRIM',
'TRIO',
'TRIP',
'TROD',
'TROT',
'TROY',
'TRUE',
'TRUG',
'TUBA',
'TUBE',
'TUBS',
'TUCK',
'TUFAS',
'TUFT',
'TUGS',
'TUIS',
'TULE',
'TUMS',
'TUNA',
'TUNE',
'TUNG',
'TUNS',
'TUPS',
'TURD',
'TURF',
'TURK',
'TURN',
'TUSH',
'TUSK',
'TUTS',
'TWAS',
'TWAT',
'TWIG',
'TWIN',
'TWIT',
'TYPE',
'TYRE',
'TYRO',
'UBER',
'UDON',
'UGHS',
'UGLY',
'UKES',
'ULAN',
'ULNA',
'ULUS',
'ULVA',
'UMBO',
'UMPS',
'UNAI',
'UNAU',
'UNCI',
'UNCO',
'UNDE',
'UNDO',
'UNDY',
'UNIT',
'UNTO',
'UPAS',
'UPBY',
'UPDO',
'UPON',
'URBS',
'URDS',
'UREA',
'URES',
'URGE',
'URIC',
'URNS',
'URSA',
'URUS',
'USED',
'USER',
'USES',
'UTAS',
'UTES',
'UVEA',
'UVEAL',
'UVULA',
'VACS',
'VAGI',
'VAIL',
'VAIN',
'VAIR',
'VALE',
'VAMP',
'VANE',
'VANG',
'VANS',
'VARA',
'VARY',
'VASA',
'VASE',
'VAST',
'VATS',
'VAWS',
'VEAL',
'VEEP',
'VEER',
'VEIL',
'VEIN',
'VELA',
'VENA',
'VEND',
'VENT',
'VERA',
'VERB',
'VERT',
'VERY',
'VEST',
'VETO',
'VETS',
'VEXA',
'VEXT',
'VIAL',
'VIBE',
'VICE',
'VIDE',
'VIED',
'VIER',
'VIES',
'VIEW',
'VIGA',
'VILE',
'VILL',
'VIMS',
'VINA',
'VINE',
'VINO',
'VINY',
'VIOL',
'VIRL',
'VISA',
'VISE',
'VITA',
'VIVA',
'VIVE',
'VOES',
'VOID',
'VOLE',
'VOLT',
'VOTE',
'VOWS',
'VRIL',
'VUGG',
'VUGH',
'VUGS',
'WABS',
'WACK',
'WADE',
'WADI',
'WADS',
'WADY',
'WAES',
'WAFF',
'WAFT',
'WAGE',
'WAGS',
'WAIF',
'WAIL',
'WAIN',
'WAIR',
'WAIT',
'WAKE',
'WALE',
'WALK',
'WALL',
'WALY',
'WAME',
'WAND',
'WANE',
'WANG',
'WANK',
'WANS',
'WANT',
'WANY',
'WAPS',
'WARD',
'WARE',
'WARK',
'WARM',
'WARN',
'WARP',
'WARS',
'WART',
'WARY',
'WASH',
'WASP',
'WAST',
'WATS',
'WATT',
'WAUK',
'WAUL',
'WAUR',
'WAVE',
'WAVY',
'WAWL',
'WAWN',
'WAWS',
'WAXY',
'WAYS',
'WEAK',
'WEAL',
'WEAN',
'WEAR',
'WEBS',
'WEDS',
'WEED',
'WEEL',
'WEEN',
'WEEP',
'WEER',
'WEES',
'WEET',
'WEFT',
'WELD',
'WELL',
'WELT',
'WEND',
'WENS',
'WENT',
'WEPT',
'WERE',
'WERT',
'WEST',
'WETS',
'WHA',
'WHEE',
'WHET',
'WHID',
'WHIG',
'WHIM',
'WHIN',
'WHIP',
'WHIR',
'WHIT',
'WHIZ',
'WHO',
'WHOA',
'WHOM',
'WHOP',
'WHUP',
'WHYS',
'WICH',
'WICK',
'WIDE',
'WIFE',
'WIGS',
'WILD',
'WILE',
'WILL',
'WILT',
'WILY',
'WIND',
'WINE',
'WING',
'WINK',
'WINO',
'WINS',
'WINY',
'WIPE',
'WIRE',
'WIRY',
'WISE',
'WISH',
'WISP',
'WISS',
'WIST',
'WITE',
'WITH',
'WITS',
'WIVE',
'WOAD',
'WOES',
'WOKE',
'WOKS',
'WOLD',
'WOLF',
'WOMB',
'WONK',
'WONS',
'WONT',
'WOOD',
'WOOF',
'WOOL',
'WOOS',
'WORD',
'WORE',
'WORK',
'WORM',
'WORN',
'WORT',
'WOST',
'WOTS',
'WOVE',
'WOWS',
'WRAP',
'WREN',
'WRIT',
'WYCH',
'WYES',
'WYLE',
'WYND',
'WYNN',
'WYNS',
'WYTE',
'XRAY',
'XYST',
'YACK',
'YAFF',
'YAGI',
'YAHU',
'YAKS',
'YALE',
'YAMS',
'YANG',
'YANK',
'YAPP',
'YAPS',
'YARD',
'YARE',
'YARN',
'YAUD',
'YAUP',
'YAWL',
'YAWN',
'YAWS',
'YAWP',
'YAWS',
'YAWP',
'YAWL',
'YAWN',
'YEAN',
'YEAR',
'YEAS',
'YECH',
'YELK',
'YELL',
'YELM',
'YELP',
'YENS',
'YEPS',
'YERK',
'YESK',
'YETI',
'YETT',
'YEUK',
'YEWS',
'YIDS',
'YILL',
'YINS',
'YIPE',
'YIPS',
'YIRD',
'YLEM',
'YOBS',
'YOCK',
'YODH',
'YODS',
'YOGA',
'YOGH',
'YOGI',
'YOKE',
'YOKS',
'YOLK',
'YOND',
'YONI',
'YORE',
'YORK',
'YOUR',
'YOWE',
'YOWL',
'YUCH',
'YUCK',
'YUGA',
'YUKS',
'YULE',
'YUMP',
'YURT',
'YUTZ',
'YWIS',
'ZAGS',
'ZANY',
'ZAPS',
'ZARF',
'ZEAL',
'ZEAS',
'ZEBU',
'ZEDS',
'ZEES',
'ZEIN',
'ZELS',
'ZEPS',
'ZERK',
'ZERO',
'ZEST',
'ZETA',
'ZIGS',
'ZILL',
'ZINC',
'ZING',
'ZINS',
'ZIPS',
'ZITE',
'ZOEA',
'ZOIC',
'ZONA',
'ZONE',
'ZONK',
'ZOOM',
'ZOON',
'ZOOS',
'ZORI',
'ZYME'
]